SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [FF].[NFLTeam] NOCHECK CONSTRAINT ALL
GO
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('San Francisco', '49ers', 'SF', 8, 1, 1944)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Baltimore ', 'Ravens', 'BAL', 11, 2, 1996)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Green Bay ', 'Packers', 'GB', 9, 3, 1921)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Houston ', 'Texans', 'HOU', 10, 4, 1999)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Philadelphia ', 'Eagles', 'PHI', 7, 5, 1933)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Pittsburgh ', 'Steelers', 'PIT', 12, 6, 1933)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('New York', 'Giants', 'NYG', 8, 7, 1925)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Detroit ', 'Lions', 'DET', 9, 8, 1930)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('New England ', 'Patriots', 'NE', 10, 9, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Chicago ', 'Bears', 'CHI', 9, 10, 1920)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Buffalo ', 'Bills', 'BUF', 9, 11, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('New York', 'Jets', 'NYJ', 11, 12, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Seattle ', 'Seahawks', 'SEA', 4, 13, 1974)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Dallas ', 'Cowboys', 'DAL', 11, 14, 1960)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Atlanta ', 'Falcons', 'ATL', 9, 15, 1965)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Denver ', 'Broncos', 'DEN', 4, 16, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Arizona ', 'Cardinals', 'ARI', 4, 17, 1920)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Jacksonville ', 'Jaguars', 'JAX', 11, 18, 1993)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Cincinnati ', 'Bengles', 'CIN', 4, 19, 1967)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Minnesota ', 'Vikings', 'MIN', 10, 20, 1960)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('San Diego ', 'Chargers', 'SD', 10, 21, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Miami ', 'Dolphins', 'MIA', 5, 22, 1965)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Kansas City ', 'Chiefs', 'KC', 6, 23, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Tennessee ', 'Titans', 'TEN', 9, 24, 1959)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Carolina ', 'Panthers', 'CAR', 12, 25, 1993)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('New Orleans ', 'Saints', 'NO', 6, 26, 1966)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Oakland ', 'Raiders', 'OAK', 5, 27, 1960)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Washington ', 'Redskins', 'WAS', 10, 28, 1932)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('St. Louis ', 'Rams', 'STL', 4, 29, 1937)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Tampa Bay ', 'Buccaneers', 'TB', 7, 30, 1974)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Cleveland ', 'Browns', 'CLE', 4, 31, 1944)
INSERT INTO [FF].[NFLTeam] ([Location], [Name], [Code], [Bye], [Rank], [Inception]) VALUES ('Indianapolis ', 'Colts', 'IND', 10, 32, 1953)
GO
