SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [FF].[League](
	[LeagueId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_League] PRIMARY KEY CLUSTERED 
(
	[LeagueId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GRANT DELETE ON [FF].[League] TO [DataUser] AS [dbo]
GRANT INSERT ON [FF].[League] TO [DataUser] AS [dbo]
GRANT SELECT ON [FF].[League] TO [DataUser] AS [dbo]
GRANT UPDATE ON [FF].[League] TO [DataUser] AS [dbo]
GO
